/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { MedicalOrder, SystemUser } from '../types';

// Let's define some preloaded users/staff for demonstration
export const INITIAL_USERS: SystemUser[] = [
  {
    id: 'USR-01',
    name: 'María Elena',
    lastName: 'Martínez',
    role: 'medico',
    identifier: 'Mat. 44102',
    email: 'm.martinez@suarez.gob.ar',
    status: 'Activo',
  },
  {
    id: 'USR-02',
    name: 'Horacio Lucio',
    lastName: 'Altieri',
    role: 'medico',
    identifier: 'Mat. 39185',
    email: 'h.altieri@suarez.gob.ar',
    status: 'Activo',
  },
  {
    id: 'USR-03',
    name: 'Ada Maria',
    lastName: 'Gonzalez',
    role: 'paciente',
    identifier: '14.283.991',
    email: 'ada.gonzalez@gmail.com',
    status: 'Activo',
  },
  {
    id: 'USR-04',
    name: 'Juan Carlos',
    lastName: 'Pérez',
    role: 'paciente',
    identifier: '22.391.802',
    email: 'juancperez@outlook.com',
    status: 'Activo',
  },
  {
    id: 'USR-05',
    name: 'Santi',
    lastName: 'Olaciregui',
    role: 'admin',
    identifier: 'admin.santi',
    email: 'santi.olaciregui13@gmail.com',
    status: 'Activo',
  }
];

// Let's define some preloaded orders for demonstration
export const INITIAL_ORDERS: MedicalOrder[] = [
  {
    id: 'REC-3049',
    patientName: 'Ada Maria',
    patientLastName: 'Gonzalez',
    patientDni: '14.283.991',
    patientBirthDate: '1980-01-01',
    patientEmail: 'ada.gonzalez@gmail.com',
    patientPhone: '+5492926441111',
    deliveryMethod: 'both',
    obraSocial: 'PAMI (Inssjp)',
    obraSocialNumber: '1502938472901',
    medicationMethod: 'foto',
    medicationText: 'Enalapril 10mg (2 cajas/mes) - Laboratorio Roemmers',
    diagnostic: 'Hipertensión Crónica',
    medicationPhotoUrl: 'MOCK_BOX_PHOTO',
    medicationPhotoName: 'foto_caja_del_remedio.jpg',
    paymentReceiptUrl: 'MOCK_RECEIPT_PHOTO',
    paymentReceiptName: 'transferencia_galicia.png',
    paymentAmount: '1200',
    paymentDate: '2026-06-22',
    status: 'Pendiente',
    createdAt: '2026-06-22T15:30:00.000Z',
    recipePdfUrl: null,
    recipePdfName: null,
  },
  {
    id: 'REC-2981',
    patientName: 'Juan Carlos',
    patientLastName: 'Pérez',
    patientDni: '22.391.802',
    patientBirthDate: '1970-05-15',
    patientEmail: 'juancperez@outlook.com',
    patientPhone: '+5492926442222',
    deliveryMethod: 'email',
    obraSocial: 'IOMA',
    obraSocialNumber: '402910392019',
    medicationMethod: 'manual',
    medicationText: 'Metformina 850mg (1 caja) y Losartán 50mg (2 cajas) - Crónicos',
    diagnostic: 'Diabetes Tipo 2 e Hipertensión',
    medicationPhotoUrl: 'MOCK_BOX_PHOTO_2',
    medicationPhotoName: 'carton_metformina_losartan.jpg',
    paymentReceiptUrl: 'MOCK_RECEIPT_PHOTO_2',
    paymentReceiptName: 'comprobante_banco_provincia.pdf',
    paymentAmount: '2000',
    paymentDate: '2026-06-20',
    status: 'Emitida',
    createdAt: '2026-06-20T09:15:00.000Z',
    updatedAt: '2026-06-20T11:40:00.000Z',
    recipePdfUrl: 'MOCK_RECIPE_PDF_READY',
    recipePdfName: 'receta_firmada_perez_ioma.pdf',
    doctorNotes: 'Receta cargada en el portal de IOMA. Se adjunta copia digital para control.',
  },
  {
    id: 'REC-3011',
    patientName: 'Clara Mabel',
    patientLastName: 'Rodriguez',
    patientDni: '18.490.551',
    patientBirthDate: '1965-08-22',
    patientEmail: 'claramrodriguez@gmail.com',
    patientPhone: '+5492926443333',
    deliveryMethod: 'both',
    obraSocial: 'OSDE',
    obraSocialNumber: '113829109',
    medicationMethod: 'foto',
    medicationText: 'L-Tiroxina 100mcg - T4 (3 cajas para tratamiento trimestral)',
    diagnostic: 'Hipotiroidismo Crónico',
    medicationPhotoUrl: 'MOCK_BOX_PHOTO_3',
    medicationPhotoName: 'envase_t4_tiroxina.jpg',
    paymentReceiptUrl: 'MOCK_RECEIPT_PHOTO_3',
    paymentReceiptName: 'screenshot_mercado_pago.jpg',
    paymentAmount: '1200',
    paymentDate: '2026-06-21',
    status: 'En revisión',
    createdAt: '2026-06-21T18:45:00.000Z',
    recipePdfUrl: null,
    recipePdfName: null,
  }
];

export const BANK_DETAILS = {
  bank: 'Banco de la Provincia de Buenos Aires',
  accountType: 'Caja de Ahorros Especial',
  cbu: '0140304301304905910293',
  alias: 'recetas.coronelsuarez',
  titular: 'Dra. María Elena Martínez (Mat. 44102)',
  costPerPrescription: '1.200 por receta (sin cargo para jubilados PAMI con subsidio social, sugerido de colaboración)',
};
